export const data = [
    {
        "id": 1,
        "title": "Breaking Bad",
        "poster": "breaking",
        "genre": "Drama",
        "episodes": "62",
        "rating": 9.4,
    },
    {
        "id": 2,
        "title": "Chernobyl",
        "poster": "chernobyl",
        "genre": "History",
        "episodes": "5",
        "rating": 9.3,
    },
    {
        "id": 3,
        "title": "The Sopranos",
        "poster": "sopranos",
        "genre": "Drama",
        "episodes": "86",
        "rating": 9.2,
    },
    {
        "id": 4,
        "title": "The Wire",
        "poster": "wire",
        "genre": "Drama",
        "episodes": "60",
        "rating": 9.2,
    },
    {
        "id": 5,
        "title": "Band of Brothers",
        "poster": "bob",
        "genre": "History",
        "episodes": "10",
        "rating": 9.2,
    },
    {
        "id": 6,
        "title": "Game of Thrones",
        "poster": "got",
        "genre": "Drama",
        "episodes": "73",
        "rating": 9.0,
    },
    {
        "id": 7,
        "title": "Mr. Robot",
        "poster": "robot",
        "genre": "Drama",
        "episodes": "45",
        "rating": 9.0,
    },
    {
        "id": 8,
        "title": "True Detective",
        "poster": "detective",
        "genre": "Drama",
        "episodes": "25",
        "rating": 8.9,
    },
    {
        "id": 9,
        "title": "The Office",
        "poster": "office",
        "genre": "Comedy",
        "episodes": "188",
        "rating": 8.8,
    },
    {
        "id": 10,
        "title": "Better Call Saul",
        "poster": "bcs",
        "genre": "Drama",
        "episodes": "63",
        "rating": 8.8,
    },
    {
        "id": 11,
        "title": "Silo",
        "poster": "silo",
        "genre": "Drama",
        "episodes": "10",
        "rating": 8.2,
    },
    {
        "id": 12,
        "title": "Succession",
        "poster": "succession",
        "genre": "Drama",
        "episodes": "39",
        "rating": 8.8,
    },
    {
        "id": 13,
        "title": "The Bear",
        "poster": "bear",
        "genre": "Drama",
        "episodes": "18",
        "rating": 8.4,
    },
    {
        "id": 14,
        "title": "Black Mirror",
        "poster": "mirror",
        "genre": "Sci-Fi",
        "episodes": "27",
        "rating": 8.8,
    }
]